Feature/tag filtering
ABRASAX3/abrasax pull request #10
Opened 2024-05-29 08:15 UTC by taehuiii

2024-05-29 10:13 UTC, T0nixx requested changes

2024-05-29 10:13 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/repository/PostRepository.kt
> +    fun findByStringifiedTagsLike(tag: String): List<Post>?
List<Post>를 return 한다면 만약에 해당하는 태그를 가진 Post가 없다면 빈 배열을 return하는게 일반적이라고 생각하는데 어떠신가요? 그리고 List<Post> 받아오려면 fun findAllByStringifiedTagsLike(like: String): List<Post> 가 되어야 할 것 같아요

2024-05-29 10:13 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val post = postRepository.findByStringifiedTagsLike(tag) ?: throw TagNotFoundException(tag)
위에서 List<Post>를 받아오면 throw하는 쪽이 필요 없을 것 같아요

2024-05-30 08:46 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/repository/PostRepository.kt
> +    fun findByStringifiedTagsLike(tag: String): List<Post>?
리턴 부분 List<Post>로 수정했으니 확인부탁드려요!
그리고 findAll부분은 처음에 그렇게 수정했는데 order, pagination기능을 추가하는 과정에서 jpa 쿼리메서드가 많이 길어져서 찾아보다보니 findBy = findAllBy 로 동일한 동작으로 조건에 맞는 모든 엔티티를 조회하고, 단건조회는 findOneBy로 조회한다고 해서 우선은 조금이나마 길이를 줄여보고자 All을 뺐는데 괜찮을까요?

2024-05-30 08:47 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val post = postRepository.findByStringifiedTagsLike(tag) ?: throw TagNotFoundException(tag)
수정했습니다!

2024-05-30 10:44 UTC, T0nixx requested changes

2024-05-30 10:44 UTC, T0nixx commented on src/main/resources/application.yml
> +jpa:
이 부분 없어도 되시는지 체크해주시고 없어도 괜찮으시면 빼고 올려주세요.
낮에 형조님이랑 저도 안됐었는데 시간이 지나니까 되더라구요.

2024-05-30 10:44 UTC, T0nixx commented on src/main/resources/static/index.html
이 파일은 혹시 왜 생성된걸까요?

2024-05-30 10:44 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/controller/PostController.kt
> +        @RequestParam pageNumber: Int,
pageNumber와 PageSize도 기본 값을 넣어주고 nullable해도 될 것 같은데 어떻게 생각하세요?

2024-05-30 10:44 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/controller/PostController.kt
> +        @RequestParam sortDirection: String
sortDirection을 처음부터 Enum으로 받을 수도 있는데 String으로 받으신 이유가 있나요?

2024-05-30 10:44 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +    fun getCurrentTime(): LocalDateTime {
이 메소드는 PostService에 있어야만 하는 비즈니스 로직이 아니라고 생각해요. 
혹시 여기에 정의하신 이유가 따로 있을까요?

2024-05-30 10:44 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val posts = postRepository.findByCreatedAtBeforeAndDeletedAtIsNull(cursorCreatedAt, pageable)
CreatedAtBefore로 하시면 sortDirection이 Desc일 때는 정상적으로 작동하지만 Asc일 때는 CreatedAtAfter 가 되어야 할 것 같아요.
sortDirection으로 분기해서 처리해야 할 것 같습니다.

2024-05-30 10:44 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val posts = postRepository.findByStringifiedTagsEqualsAndCreatedAtBeforeAndDeletedAtIsNull(
상동합니다.

2024-05-30 10:45 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/repository/PostRepository.kt
> +    fun findByStringifiedTagsLike(tag: String): List<Post>?
동작에 문제 없는 것 확인했습니다. 괜찮을 것 같아요.

2024-05-31 03:54 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/controller/PostController.kt
> +        @RequestParam pageNumber: Int,
넵 반영했습니다!

2024-05-31 03:54 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/controller/PostController.kt
> +        @RequestParam sortDirection: String
ENUM으로 변경했습니다~!

2024-05-31 03:56 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +    fun getCurrentTime(): LocalDateTime {
메소드 삭제하고 createPageableAndCursor메소드에서 필요시에 직접 LocalDateTime.now()를 넣어주는 식으로 변경했습니다.

2024-05-31 03:56 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val posts = postRepository.findByCreatedAtBeforeAndDeletedAtIsNull(cursorCreatedAt, pageable)
넵 반영했습니다~!

2024-05-31 03:57 UTC, taehuiii commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val posts = postRepository.findByStringifiedTagsEqualsAndCreatedAtBeforeAndDeletedAtIsNull(
containing이 like와 %tag%를 합친 쿼리어서 containing으로 변경해봤습니다!

2024-05-31 07:13 UTC, T0nixx approved these changes

2024-05-31 07:13 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/service/PostService.kt
> +        val sort = Sort.by(sortDirection.toSpringSortDirection(), "createdAt")
Order by를 빼고 sort를 만들어서 처리하신게 좋네요

2024-05-31 07:14 UTC, merged