feat: Authentication
ABRASAX3/abrasax pull request #11
Opened 2024-05-30 07:46 UTC by kotlin2024

2024-05-30 08:16 UTC, T0nixx requested changes

2024-05-30 08:16 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/exception/GlobalExceptionHandler.kt
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(ErrorResponse(message = ex.message))
이 부분 다시 찾아보니 형조님 말씀대로  NOT AUTHORIZED가 맞더라구요 수정부탁드립니다.

2024-05-30 08:16 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/controller/MemberController.kt
> +//    @PostMapping("/login")
이 부분 authentication에 들어갔으니 지워주세요

2024-05-30 08:16 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +        private fun checkingDuplicatedPassword(currentPassword: String, newPassword: String){
동사의 이름은 동사로 해주세요 checkDuplicatePassword면 좋을 것 같아요

2024-05-30 08:16 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +            if(currentPassword==newPassword){
이거 현재 코드의 흐름을 따라가면 currentPassword와 newPassword가 둘다 encoding된 상태인데요.
제가 아까 말씀드렸던 것 처럼 같은 패스워드여도 encoding할 때마다 salt가 추가되어서 다른 값으로 encoding돼요.
그래서 이 부분은 Model 안보다는 Service에서 request로 들어온 두 값을 비교하고 예외처리를 하는 게 좋을 것 같아요.

2024-05-30 08:16 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
>          stringifiedSocialAccounts = ListStringifyHelper.stringifyList(newSocialAccounts)
socialAccounts의 길이에 대한 validation이 빠진 것 같아요

2024-05-30 11:48 UTC, kotlin2024 commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/controller/MemberController.kt
> +//    @PostMapping("/login")
member controller와 service에 있는 signup과 login부분은 authentication에 동일부분이 있어서 삭제했습니다

2024-05-30 11:49 UTC, kotlin2024 commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +        private fun checkingDuplicatedPassword(currentPassword: String, newPassword: String){
checkingDuplicatedPassword함수 대신에updatePassword함수 내에  if (currentPassword == newPassword) {
            throw IllegalArgumentException("새로운 비밀번호와 현재 비밀번호가 동일함")
        }의 코드를 추가하여 기능을 구현했습니다

2024-05-30 11:50 UTC, kotlin2024 commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
>          stringifiedSocialAccounts = ListStringifyHelper.stringifyList(newSocialAccounts)
validateSocialAccounts 함수를 새로 만들었습니다

2024-05-30 11:53 UTC, kotlin2024 commented on src/main/kotlin/com/teamsparta/abrasax/domain/exception/GlobalExceptionHandler.kt
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(ErrorResponse(message = ex.message))
해당 부분 HttpStatus.UNAUTHORIZED로 수정했습니다

2024-05-30 12:05 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +        //validatePassword(newPassword)
이것도 지워주세요

2024-05-30 12:05 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +            )
SignUpRequest에 해당내용이 빠져있어서 Service 쪽에서 없는 걸 넣는거 보다 원래처럼 Model 안에서 빈 문자열을 넣는게 좋을 것 같은데 어떻게 생각하세요?

2024-05-30 12:05 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +
여기도 서비스로 이미 뺐으니 지워주세요

2024-05-30 12:05 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/model/Member.kt
> +                throw IllegalArgumentException("Invalid nickname format.")
ㄱ-ㅎ가-힣 도 배열안에 넣으면 한글도 입력받을 수 있는데 어떻게 생각하세요?

2024-05-31 01:43 UTC, T0nixx approved these changes
확인했습니다. 머지할게요

2024-05-31 01:43 UTC, merged