feat: post Validation
ABRASAX3/abrasax pull request #12
Opened 2024-05-30 14:22 UTC by DanDanjoo

2024-05-30 15:25 UTC, T0nixx requested changes

2024-05-30 15:25 UTC, T0nixx commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-validation")
annotation을 이용해서 validate 하지 않으니 지워주시면 좋을 것 같아요

2024-05-30 15:25 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/exception/PostValidationException.kt
> +class InvalidDuplicateTagException(message: String) : RuntimeException(message)
이 부분은 다른 모델들은 지금 IllegalArgumentException으로 퉁쳐져 있는 부분이 많은데요 제 생각엔 Model 내부에서 validate 관련한 예외들은 튜터님께서 말씀하셨던 ModelInvariantExeption 을 하나 만들어서 일괄적으로 처리하는 건 어떨까요?
커스텀 예외를 만드신 부분은 정말 좋습니다.

2024-05-30 15:25 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/controller/MemberController.kt
> +import jakarta.validation.Valid
이 부분을 미처 못지우신 것 같아요

2024-05-30 15:25 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/controller/MemberController.kt
> +    fun signUp(@Valid @RequestBody signUpRequest: SignUpRequest): ResponseEntity<MemberResponse> {
상동합니다.

2024-05-30 15:25 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/member/dto/SignUpRequest.kt
> +import jakarta.validation.constraints.Email
이 파일에 대해서도 모두 지워주세요

2024-05-30 15:25 UTC, T0nixx commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/model/Post.kt
> +        private fun validateTagListSize(tagList: List<String>) {
tagList라는 이름을 사용하신 이유가 있을까요?

2024-05-30 15:36 UTC, DanDanjoo commented on src/main/kotlin/com/teamsparta/abrasax/domain/exception/PostValidationException.kt
> +class InvalidDuplicateTagException(message: String) : RuntimeException(message)
감사합니다! 예외 처리에 대해서 알려주신 부분이 큰 도움이 됐습니다.   말씀해주신 부분 수정하겠습니다.

2024-05-30 16:05 UTC, DanDanjoo commented on src/main/kotlin/com/teamsparta/abrasax/domain/post/model/Post.kt
> +        private fun validateTagListSize(tagList: List<String>) {
매개변수를 미처 못 바꿨네요! 수정하겠습니다.

2024-05-31 06:10 UTC, T0nixx approved these changes

2024-05-31 06:10 UTC, T0nixx commented
main 에서 pull 한번 하시고 squash and merge 해주세요

2024-05-31 06:56 UTC, merged